[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["Aaron Steers <aj@airbyte.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
airbyte = "^0.18.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
