[tool.poe.tasks]

[tool.poe.tasks.install]
shell = "poetry install --all-extras"

[tool.poe.tasks.lock]
shell = "poetry lock"

[tool.poe.tasks.pytest]
shell = "pytest"

[tool.poe.tasks.pytest-fast]
shell = "pytest --ff -m 'not slow and not requires_creds'"

[tool.poe.tasks.coverage]
shell = "pytest --cov=. --cov-report=term-missing"

[tool.poe.tasks.coverage-html]
shell = "pytest --cov=. --cov-report=html"

[tool.poe.tasks.check]
shell = "ruff check . && mypy ."

[tool.poe.tasks.fix]
shell = "ruff format . && ruff check --fix -s || ruff format ."

[tool.poe.tasks.fix-and-check]
shell = "poe fix && poe check"
