[tool.poe.tasks]
install.shell = "poetry install --all-extras"
lock.shell = "poetry lock"
pytest.shell = "pytest"
pytest-fast.shell = "pytest --ff -m 'not slow and not requires_creds'"
coverage.shell = "pytest --cov=. --cov-report=term-missing"
coverage-html.shell = "pytest --cov=. --cov-report=html"
check.shell = "ruff check . && mypy ."
fix.shell = "ruff format . && ruff check --fix -s || ruff format ."
fix-and-check.shell = "poe fix && poe check"
