[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "airbyte-destination-milvus"
version = "0.0.48"
description = "Airbyte destination implementation for Milvus."
authors = ["Airbyte <contact@airbyte.io>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/destinations/milvus"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"

[[tool.poetry.packages]]
include = "destination_milvus"

[tool.poetry.dependencies]
python = "^3.10,<3.12"
airbyte-cdk = {version = "^6.27.0", extras = ["vector-db-based"]}
pymilvus = ">=2.5.4,<2.6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
ruff = "^0.3.2"
mypy = "^1.9.0"
setuptools = "^69.0.0"  # Required by pymilvus for pkg_resources

[tool.poetry.scripts]
destination-milvus = "destination_milvus.run:run"
