name: Connector Ops CI - Gradle Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  S3_BUILD_CACHE_ACCESS_KEY_ID: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
  S3_BUILD_CACHE_SECRET_KEY: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      java: ${{ steps.changes.outputs.java }}

    steps:
      - name: Checkout Airbyte
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - id: changes
        uses: dorny/paths-filter@v2
        with:
          # Note: expressions within a filter are OR'ed
          filters: |
            java:
              - '**/*.java'
              - '**/*.gradle'
              - '**/*.kt'
              - 'airbyte-cdk/java/**/*'
              - 'airbyte-cdk/bulk/**/*'

  gradle-matrix:
    needs:
      - changes
    if: needs.changes.outputs.java == 'true'
    runs-on: linux-20.04-large # Custom runner, defined in GitHub org settings
    strategy:
      matrix:
        gradle-task:
          - name: compile
            command: assemble testClasses
          - name: spotbugs
            command: spotbugsMain spotbugsTest
          - name: unit-tests
            command: test -x spotbugsMain -x spotbugsTest
          - name: integration-tests
            command: integrationTest -x test -x spotbugsMain -x spotbugsTest
    name: Gradle ${{ matrix.gradle-task.name }}
    timeout-minutes: 60
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Docker login
        if: github.event.pull_request.head.repo.fork != true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Run ${{ matrix.gradle-task.name }}
        uses: burrunan/gradle-cache-action@v1
        env:
          CI: true
        with:
          job-id: gradle-${{ matrix.gradle-task.name }}
          read-only: ${{ github.ref != 'refs/heads/master' }}
          gradle-distribution-sha-256-sum-warning: false
          concurrent: true
          arguments: --scan ${{ matrix.gradle-task.command }} -DskipSlowTests=true

  set-instatus-incident-on-failure:
    name: Create Instatus Incident on Failure
    runs-on: ubuntu-24.04
    needs:
      - gradle-matrix
    if: ${{ failure() && github.ref == 'refs/heads/master' }}
    steps:
      - name: Call Instatus Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.INSTATUS_CONNECTOR_CI_WEBHOOK_URL }}
          body: '{ "trigger": "down", "status": "HASISSUES" }'

  set-instatus-incident-on-success:
    name: Create Instatus Incident on Success
    runs-on: ubuntu-24.04
    needs:
      - gradle-matrix
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    steps:
      - name: Call Instatus Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.INSTATUS_CONNECTOR_CI_WEBHOOK_URL }}
          body: '{ "trigger": "up" }'

  notify-failure-slack-channel:
    name: "Notify Slack Channel on Build Failures"
    runs-on: ubuntu-24.04
    needs:
      - gradle-matrix
    if: ${{ failure() && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v4
      - name: Match GitHub User to Slack User
        id: match-github-to-slack-user
        uses: ./.github/actions/match-github-to-slack-user
        env:
          AIRBYTE_TEAM_BOT_SLACK_TOKEN: ${{ secrets.SLACK_AIRBYTE_TEAM_READ_USERS }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to OSS Build Failure Slack Channel
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
        with:
          args: >-
            {\"channel\":\"C03BEADRPNY\", \"blocks\":[
            {\"type\":\"divider\"},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" Merge to OSS Master failed! :bangbang: \n\n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged by_: *${{ github.actor }}* \n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<@${{ steps.match-github-to-slack-user.outputs.slack_user_ids }}> \n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" :octavia-shocked: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Action Run> :octavia-shocked: \n\"}},
            {\"type\":\"divider\"}]}

  notify-failure-slack-channel-fixed-broken-build:
    name: "Notify Slack Channel on Build Fixes"
    runs-on: ubuntu-24.04
    needs:
      - gradle-matrix
    if: ${{ success() && github.event.pull_request.head.repo.fork != true }}
    steps:
      - name: Get Previous Workflow Status
        uses: Mercymeilya/last-workflow-status@v0.3
        id: last_status
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # To avoid clogging up the channel, only publish build success if the previous build was a failure since this means the build was fixed.
      - name: Publish Build Fixed Message to OSS Build Failure Slack Channel
        if: ${{ steps.last_status.outputs.last_status == 'failure' }}
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN_AIRBYTE_TEAM }}
        with:
          args: >-
            {\"channel\":\"C03BEADRPNY\", \"blocks\":[
            {\"type\":\"divider\"},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" OSS Master Fixed! :white_check_mark: \n\n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"_merged by_: *${{ github.actor }}* \n\"}},
            {\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\" :octavia-rocket: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View Action Run> :octavia-rocket: \n\"}},
            {\"type\":\"divider\"}]}
